// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3kq8M5JtCOQtrtYGNSqsHhaI__FP6GTE',
    appId: '1:723788646343:web:c42ac4018ead28fb6fbbe2',
    messagingSenderId: '723788646343',
    projectId: 'bottlecash-4577a',
    authDomain: 'bottlecash-4577a.firebaseapp.com',
    databaseURL: 'https://bottlecash-4577a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bottlecash-4577a.appspot.com',
    measurementId: 'G-T2V3N1JEBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wW0uBpYR8XA_ga5KWA4ZYB_bZhyUFHk',
    appId: '1:723788646343:android:b56841fcbf2dea856fbbe2',
    messagingSenderId: '723788646343',
    projectId: 'bottlecash-4577a',
    databaseURL: 'https://bottlecash-4577a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bottlecash-4577a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7QJM3OhTOxX5cbPlFXn17St04BEkB16g',
    appId: '1:723788646343:ios:5043a5571912b7506fbbe2',
    messagingSenderId: '723788646343',
    projectId: 'bottlecash-4577a',
    databaseURL: 'https://bottlecash-4577a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bottlecash-4577a.appspot.com',
    androidClientId: '723788646343-5c7camp8d93odm77l0cl8rcfdrm55bk2.apps.googleusercontent.com',
    iosClientId: '723788646343-67seo8s55n289kksmacug9nkcmfvg4pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminBottleCashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7QJM3OhTOxX5cbPlFXn17St04BEkB16g',
    appId: '1:723788646343:ios:5043a5571912b7506fbbe2',
    messagingSenderId: '723788646343',
    projectId: 'bottlecash-4577a',
    databaseURL: 'https://bottlecash-4577a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bottlecash-4577a.appspot.com',
    androidClientId: '723788646343-5c7camp8d93odm77l0cl8rcfdrm55bk2.apps.googleusercontent.com',
    iosClientId: '723788646343-67seo8s55n289kksmacug9nkcmfvg4pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminBottleCashApp',
  );
}
